### ISSUE TITLE
Chat not working.

### ISSUE THREAD

**Issue by ghost** [cnaude/PurpleBungeeIRC#5]
The plugin connects and join the channel but it's doesn't forward the chat or anything. I have all permissions required. 
http://pastebin.com/RAWw2PjP

**Comment by cnaude** [comment]
Did you assign the permissions on the proxy server? That's where the plugin reads the permissions from.

**Comment by cnaude** [comment]
Here's an example from my bungee config.yml.

``` yml
player_limit: 100
ip_forward: false
permissions:
  default:
  - irc.message.gamechat
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
timeout: 30000
log_commands: false
online_mode: true
servers:
```
